name: Scrape Dependents

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      language:
        required: true
        type: string
      type:
        required: true
        type: string
      min-stars:
        required: false
        type: number
        default: 10
      max-pages:
        required: false
        type: number
        default: 0
      output-dir:
        required: false
        type: string
        default: output

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci
      - name: Run scraper
        env:
          DEPENDENTS_TOKEN: ${{ secrets.DEPENDENTS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ${{ inputs.output-dir }}
          node src/scrape_dependents.mjs \
            --repo "${{ inputs.repo }}" \
            --min-stars ${{ inputs.min-stars }} \
            --max-pages ${{ inputs.max-pages }} \
            --output-dir ${{ inputs.output-dir }} \
            --language "${{ inputs.language }}" \
            --type "${{ inputs.type }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dependents-output
          path: ${{ inputs.output-dir }}/*