name: Scrape Dependents

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      language:
        required: true
        type: string
      type:
        required: true
        type: string
      min-stars:
        required: false
        type: number
        default: 100
      max-pages:
        required: false
        type: number
        default: 500
      package_id:
        required: false
        type: string
        default: ''
      output-dir:
        required: false
        type: string
        default: output

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install deps
        run: npm ci
      - name: Run scraper
        id: run-scraper
        env:
          DEPENDENTS_TOKEN: ${{ secrets.DEPENDENTS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ${{ inputs.output-dir }}
          # derive REPO_NAME as last path segment and export for later steps
          repo_full="${{ inputs.repo }}"
          repo_name="${repo_full##*/}"
          echo "REPO_NAME=${repo_name}" >> $GITHUB_ENV
          echo "repo_name=${repo_name}" >> $GITHUB_OUTPUT
          node src/scrape_dependents.mjs \
            --repo "${{ inputs.repo }}" \
            --min-stars ${{ inputs.min-stars }} \
            --max-pages ${{ inputs.max-pages }} \
            --output-dir ${{ inputs.output-dir }} \
            --package_id "${{ inputs.package_id }}" \
            --language "${{ inputs.language }}" \
            --type "${{ inputs.type }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dependents-output-${{ steps.run-scraper.outputs.repo_name }}-${{ github.run_id }}
          path: ${{ inputs.output-dir }}/*