name: Scrape All Dependents
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Read repos.json and set matrix
        id: set-matrix
        run: |
          import json, os
          with open('results/repos.json') as f:
              repos = json.load(f)
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              fh.write(f"matrix={json.dumps({'include': repos})}\n")
        shell: python

  scrape:
    needs: generate-matrix
    uses: ./.github/workflows/dependents.yml
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    with:
      repo: ${{ matrix.repo }}
      language: ${{ matrix.language }}
      type: ${{ matrix.type }}
      min-stars: 10
      max-pages: 0
      output-dir: output
