name: Scrape All Dependents
on:
  workflow_dispatch:
    inputs:
      repo_choice:
        description: "Select a repo slug to re-scrape, or 'all' to run all (default: all)"
        required: false
        default: all
        type: choice
        options:
          - all
          - mongoid
          - mongo-ruby-driver
          - node-mongodb-native
          - prisma
          - mongo-java-driver
          - mongo-python-driver
          - mongo-go-driver
          - mongo-csharp-driver
          - drizzle-orm
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Read repos.json and set matrix
        id: set-matrix
        env:
          REPO_CHOICE: ${{ github.event.inputs.repo_choice }}
        run: |
          import json, os
          choice = (os.getenv('REPO_CHOICE') or 'all').strip()
          with open('./repos.json') as f:
              repos = json.load(f)
          if choice and choice.lower() != 'all':
              repos = [r for r in repos if r.get('repo','').split('/')[-1] == choice]
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              fh.write(f"matrix={json.dumps({'include': repos})}\n")
        shell: python

  scrape:
    needs: generate-matrix
    permissions:
      contents: write
    uses: ./.github/workflows/dependents.yml
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    with:
      repo: ${{ matrix.repo }}
      language: ${{ matrix.language }}
      type: ${{ matrix.type }}
      package_id: ${{ matrix.package_id }}
      min-stars: 100
      max-pages: 500
      output-dir: output

  finalize-readme:
    needs: scrape
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Generate README from reports
        run: node src/generate_readme.mjs output
      - name: Commit and push README
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          git add output/README.md || true
          if git diff --cached --quiet; then
            echo "No README changes to commit"
          else
            git commit -m "Update aggregated README of reports (run ${{ github.run_id }})"
            git push origin HEAD
          fi
